name: Deploy alerts to NAIS
on:
  push:
    branches:
      - main
    paths:
      - '.nais/alerts.yaml'
      - '.github/workflows/deploy-alerts.yaml'
jobs:
  apply-alerts:
    name: Apply alerts to clusters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts.yaml
      - name: deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts.yaml